Repository Ebyrdeu/spring_boot_library, pull requests merged in 2024-04, with the labels that each got.

#21 #6 Creat MessageController & UserController based on the current looks o…
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/MessageController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/UserController.java
Labels: enhancement

#25 Add private field to MessageEntity
  pom.xml
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/.gitkeep
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/MessageController.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/.gitkeep
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Message.java
  src/main/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepository.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/.gitkeep
  src/main/java/dev/ebrydeu/spring_boot_library/services/MessageService.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepositoryTest.java
Labels: enhancement

#33 Integration test of controllers And Refactoring for project
  pom.xml
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/MessageController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/UserController.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Message.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/User.java
  src/main/java/dev/ebrydeu/spring_boot_library/exception/ExceptionHandling.java
  src/main/java/dev/ebrydeu/spring_boot_library/exception/Exceptions.java
  src/main/java/dev/ebrydeu/spring_boot_library/libs/Utils.java
  src/main/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepository.java
  src/main/java/dev/ebrydeu/spring_boot_library/repositories/UserRepository.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/MessageService.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/UserService.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/impl/MessageServiceImpl.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/impl/UserServiceImpl.java
  src/test/java/dev/ebrydeu/spring_boot_library/TestDataUtils.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/MessageControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/UserControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepositoryTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/UserRepositoryTest.java
  src/test/resources/application.properties
Labels: enhancement

#34 Maven local testing
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/MessageControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/UserControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepositoryTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/UserRepositoryTest.java
  src/test/resources/application.properties
Labels: bug

#32 #31 Added Auditable class and config file
  src/main/java/dev/ebrydeu/spring_boot_library/config/AuditingConfig.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Auditable.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/AuditorAwareImpl.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Message.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/User.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/MessageControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/UserControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDtoTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/MessageRepositoryTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/repositories/UserRepositoryTest.java
  src/test/resources/application.properties
Labels: enhancement, Project Requirement

#38 Home page Home.html is added.
  pom.xml
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/HomeController.java
  src/main/resources/static/index.html
  src/main/resources/templates/home.html
Labels: enhancement

#49 Test https://localhost8443/home
  .env-example
  src/main/java/dev/ebrydeu/spring_boot_library/config/SecurityConfig.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/HomeController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/WebController.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Role.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/User.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/templates/home.html
  src/main/resources/templates/user-profile-page.html
  src/test/java/dev/ebrydeu/spring_boot_library/ApplicationTests.java
  src/test/java/dev/ebrydeu/spring_boot_library/config/SecurityConfigTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/MessageControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/UserControllerTest.java
Labels: enhancement

#53 added swagger to app
  .env-example
  pom.xml
  src/main/java/dev/ebrydeu/spring_boot_library/config/AuditingConfig.java
  src/main/java/dev/ebrydeu/spring_boot_library/config/EnvironmentConfiguration.java
  src/main/java/dev/ebrydeu/spring_boot_library/config/OpenApiConfig.java
  src/main/java/dev/ebrydeu/spring_boot_library/config/SecurityConfig.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/MessageController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/UserController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/rest/MessageController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/rest/UserController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/web/HomeController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/web/SwaggerController.java
  src/main/java/dev/ebrydeu/spring_boot_library/controllers/web/WebController.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/audit/Auditable.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/audit/AuditorAwareImpl.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/MessageWithoutUserDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDto.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Message.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/Role.java
  src/main/java/dev/ebrydeu/spring_boot_library/domain/entities/User.java
  src/main/java/dev/ebrydeu/spring_boot_library/exception/ExceptionHandling.java
  src/main/java/dev/ebrydeu/spring_boot_library/exception/Exceptions.java
  src/main/java/dev/ebrydeu/spring_boot_library/providers/SwaggerAdminProvider.java
  src/main/java/dev/ebrydeu/spring_boot_library/repositories/UserRepository.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/JSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/ConflictJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/InternalServerJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/NoContentJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/NotFoundJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/message/MessageJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/message/MessagesJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/user/UserJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/responses/dto/user/UsersJSendResponse.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/impl/GoogleOAuth2ServiceImpl.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/impl/MessageServiceImpl.java
  src/main/java/dev/ebrydeu/spring_boot_library/services/impl/UserServiceImpl.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/templates/swagger-login.html
  src/test/java/dev/ebrydeu/spring_boot_library/TestDataUtils.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/MessageControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/controllers/UserControllerTest.java
  src/test/java/dev/ebrydeu/spring_boot_library/domain/dto/UserDtoTest.java
Labels: enhancement
